// src/locales/es.ts
const en = {
  translation: {
    "Help Us Help You": "Ayúdanos a Ayudarte",
    "What information do you need?": "¿Qué información necesitas?",
    "Courses": "Cursos",
    "License Procedure": "Tramite de Licencia",
    "Liberia COC": "Liberia COC",
    "Physical Examination": "Examen Médico",

    // Header
    "Course Quote": "Cotización de Cursos",
    "Select your nationality, government/institution, and the maritime courses of your interest to get a quote": "Selecciona tu nacionalidad, gobierno/institución y los cursos marítimos de tu interés para obtener una cotización",
    
    // Form Section: Personal Info
    "Personal Information": "Información Personal",
    "Complete your details to generate the quote": "Completa tus datos para generar la cotización",
    "Name": "Nombre",
    "Your name": "Tu nombre",
    "Last Name": "Apellido",
    "Your last name": "Tu apellido",
    "ID or Passport": "Cédula o Pasaporte",
    "Document number": "Número de documento",
    "Nationality": "Nacionalidad",
    "Select your nationality": "Selecciona tu nacionalidad",
    "Determines whether you use prices for Panamanians or foreigners": "Determina si usas precios para panameños o extranjeros",
    "✅ Panamanian prices": "✅ Precios panameños",
    "🌍 Foreigner prices": "🌍 Precios extranjeros",
    "Email": "Correo Electrónico",
    "you@email.com": "tu@email.com",
    "Phone": "Teléfono",
    "+1 (123) 456-7890": "+1 (123) 456-7890",
    "Search renewal courses...": "Buscar cursos de renovación...",
    "Select courses for renewal": "Selecciona cursos para renovación",
    "Select one or more courses": "Selecciona uno o más cursos",
    "Security Verification": "Verificación de Seguridad",
    "I am not a robot": "No soy un robot",

    // Form Section: Course Selection
    "Fill out the form to generate your quote": "Llena el formulario para generar tu cotización",
    "Government/Institution": "Gobierno/Institución",
    "Select the government/institution": "Selecciona el gobierno/institución",
    "A surcharge of {{surcharge}}% will be applied to the base price": "Se aplicará un recargo del {{surcharge}}% sobre el precio base",
    "No additional surcharge": "Sin recargo adicional",
    "New Maritime Courses": "Cursos Marítimos Nuevos",
    "(Search by name or abbreviation)": "(Busca por nombre o abreviación)",
    "Course Renewal": "Renovación de Cursos",
    "(Only courses that allow renewal)": "(Solo cursos que permiten renovación)",

    // Form Section: Verification & Submission
    "CAPTCHA Verification": "Verificación CAPTCHA",
    "I accept the <1>terms and conditions</1> and the <2>privacy policy</2>": "Acepto los <1>términos y condiciones</1> y la <2>política de privacidad</2>",
    "Generating quote...": "Generando cotización...",
    "Generate Quote": "Generar Cotización",
    
    // Alerts
    "Please select a government/institution.": "Por favor, selecciona un gobierno/institución.",
    "Please select your nationality.": "Por favor, selecciona tu nacionalidad.",
    "Please select at least one new or renewal course.": "Por favor, selecciona al menos un curso nuevo o de renovación.",
    "Error: There are courses selected as both new and for renewal. Please review your selection.": "Error: Hay cursos seleccionados tanto como nuevos como para renovación. Por favor, revisa tu selección.",
    "Please verify the captcha before continuing.": "Por favor, verifica el captcha antes de continuar.",
    "You must accept the terms and conditions to continue.": "Debes aceptar los términos y condiciones para continuar.",
    "There was an error submitting your quote": "Hubo un error al enviar tu cotización",

    // Confirmation View
    "Quote Generated!": "¡Cotización Generada!",
    "Your quote has been generated successfully": "Tu cotización ha sido generada exitosamente",
    "Quote Confirmed": "Cotización Confirmada",
    "Summary of your maritime course quote": "Resumen de tu cotización de cursos marítimos",
    "Total Cost": "Costo Total",
    "New: ${{newCoursesTotal}}": "Nuevos: ${{newCoursesTotal}}",
    "Renewals: ${{renewalCoursesTotal}}": "Renovaciones: ${{renewalCoursesTotal}}",
    "New Courses:": "Cursos Nuevos:",
    "Renewals:": "Renovaciones:",
    "Code: {{abbr}}": "Código: {{abbr}}",
    "(Renewal)": "(Renovación)",
    "Student Details:": "Datos del estudiante:",
    "Full name:": "Nombre completo:",
    "Document:": "Documento:",
    "Government/Institution:": "Gobierno/Institución:",
    "New Quote": "Nueva Cotización",
    "Download PDF": "Descargar PDF",
    "Verify": "Verificar",
    "Enter Code": "Ingresa el código",
    "Incorrect code. Please try again.": "Código incorrecto. Intenta de nuevo.",
    "Verification successful!": "¡Verificación exitosa!",
    "Please check your email to see the full quote." :"Por favor, revisa tu correo electrónico para ver la cotización completa.",
    "License Application":"Solicitud de Licencia",
    "Complete the form to receive personalized information" : "Completa el formulario para recibir información personalizada",
    "License Information ": "Información sobre las licencias",
    "We will be in touch with you shortly.":"En poco tiempo estaremos contactándole.",
    "Thank you for your interest!": "¡Gracias por su interés!",
    "Click for Upload":"Haga clic para subir",
    "or drag here": "o arrastre aquí",
    "Submit":"Enviar",
    "Write your query here about the licenses you need...":"Escribe aquí tu consulta sobre las licencias que necesitas...",
    "Medical Certificate Form": "Formulario para Certificado Médico",
    "Position on-board": "Posición a Bordo",
    "Complete Name": "Nombre completo",
    "Identity Document": "Documento de Identidad",
    "Passport or ID Card": "Pasaporte o Cédula",
    "Weight": "Peso",
    "Height": "Altura",
    "Address": "Dirección",
    "Eyeglasses": "Anteojos",
    "Medical Information": "Información Médica",
    "Medical Conditions": "Condiciones Médicas",
    "Do you have any medical conditions?": "¿Tienes alguna condición médica?",
    "Medical Prescription" : "Prescripción Médica",
    "Last Surgery": "Última Cirugía",
    "(if applicable, indicate date, reason and current condition, or N/A)": "(si aplica, indica fecha, motivo y estado actual, o N/A)",
    "COVID Information": "Información COVID",
    "COVID Vaccine": "Vacuna COVID",
    "Date of last test (or N/A)": "Fecha de última prueba (o N/A)",
    "Date or N/A": "Fecha o N/A",
    "Last time positive" : "Última vez positivo",
    "Last COVID Test" : "Última prueba COVID",
    "Physical Exams Only Panama and for Cook's License": "Exámenes físicos solo Panamá y para Licencia de Cocinero",
    "Physical Examinations for Panama and Cook's license  (if not applicable, you can leave them blank)": "Exámenes físicos para Panamá y licencia de cocinero (si no aplica, puedes dejarlos en blanco)",
    "It's not you, it's us": "No eres tú, somos nosotros",
    "Go to home page" :"Volver a la página de inicio",
    "Blood count": "Hemograma Completo",
    "Chemistry": "Química (Creatinina, Glucosa)",
    "RH type": "Tipo RH",
    "Urinalysis": "Análisis de Orina",
    "Stool test": "Examen de Heces",
    "Drug test": "Prueba de Drogas",
    "Only required for Cook's medical certificate": "Solo requerido para el certificado médico de Cocinero",
    "Select an option": "Selecciona una opción",
    "Describe any current medical conditions (or N/A)": "Describe cualquier condición médica actual (o N/A)",
    "Current medications (or N/A)": "Medicamentos actuales (o N/A)",
    "Fecha, tipo de cirugía y estado actual (o N/A)" : "Fecha, tipo de cirugía y estado actual (o N/A)",
    "Vaccine type and dose (or N/A)": "Tipo de vacuna y dosis (o N/A)",
    "Upload Files": "Subir Archivos",
    "I agree that these courses are 100% in-person":"Estoy de acuerdo que estos cursos son 100% presenciales"
  }
};

export default en;