// src/locales/es.ts
const es = {
  translation: {
    "Ayudanos a Ayudarte": "Help Us Help You",
    "Que informacion necesitas?": "What information do you need?",
    "Cursos": "Courses",
    "Tramite de Licencia": "License Procedure",
    "Liberia COC": "Liberia COC",

    // Header
    "Cotización de Cursos": "Cotización de Cursos",
    "Selecciona tu nacionalidad, gobierno/institución y los cursos marítimos de tu interés para obtener una cotización": "Selecciona tu nacionalidad, gobierno/institución y los cursos marítimos de tu interés para obtener una cotización",
    
    // Form Section: Personal Info
    "Información Personal": "Información Personal",
    "Completa tus datos para generar la cotización": "Completa tus datos para generar la cotización",
    "Nombre": "Nombre",
    "Tu nombre": "Tu nombre",
    "Apellido": "Apellido",
    "Tu apellido": "Tu apellido",
    "Cédula o Pasaporte": "Cédula o Pasaporte",
    "Número de documento": "Número de documento",
    "Nacionalidad": "Nacionalidad",
    "Selecciona tu nacionalidad": "Selecciona tu nacionalidad",
    "Determina si usas precios para panameños o extranjeros": "Determina si usas precios para panameños o extranjeros",
    "✅ Precios panameños": "✅ Precios panameños",
    "🌍 Precios extranjeros": "🌍 Precios extranjeros",
    "Correo Electrónico": "Correo Electrónico",
    "tu@email.com": "tu@email.com",
    "Teléfono": "Teléfono",
    "+1 (123) 456-7890": "+1 (123) 456-7890",

    // Form Section: Course Selection
    "Gobierno/Institución": "Gobierno/Institución",
    "Selecciona el gobierno/institución": "Selecciona el gobierno/institución",
    "Se aplicará un recargo del {{surcharge}}% sobre el precio base": "Se aplicará un recargo del {{surcharge}}% sobre el precio base",
    "Sin recargo adicional": "Sin recargo adicional",
    "Cursos Marítimos Nuevos": "Cursos Marítimos Nuevos",
    "(Busca por nombre o abreviación)": "(Busca por nombre o abreviación)",
    "Renovación de Cursos": "Renovación de Cursos",
    "(Solo cursos que permiten renovación)": "(Solo cursos que permiten renovación)",

    // Form Section: Verification & Submission
    "Verificación CAPTCHA": "Verificación CAPTCHA",
    "Acepto los <1>términos y condiciones</1> y la <2>política de privacidad</2>": "Acepto los <1>términos y condiciones</1> y la <2>política de privacidad</2>",
    "Generando cotización...": "Generando cotización...",
    "Generar Cotización": "Generar Cotización",
    
    // Alerts
    "Por favor, selecciona un gobierno/institución.": "Por favor, selecciona un gobierno/institución.",
    "Por favor, selecciona tu nacionalidad.": "Por favor, selecciona tu nacionalidad.",
    "Por favor, selecciona al menos un curso nuevo o de renovación.": "Por favor, selecciona al menos un curso nuevo o de renovación.",
    "Error: Hay cursos seleccionados tanto como nuevos como para renovación. Por favor, revisa tu selección.": "Error: Hay cursos seleccionados tanto como nuevos como para renovación. Por favor, revisa tu selección.",
    "Por favor, verifica el captcha antes de continuar.": "Por favor, verifica el captcha antes de continuar.",
    "Debes aceptar los términos y condiciones para continuar.": "Debes aceptar los términos y condiciones para continuar.",
    "Hubo un error al enviar tu cotización": "Hubo un error al enviar tu cotización",

    // Confirmation View
    "¡Cotización Generada!": "¡Cotización Generada!",
    "Tu cotización ha sido generada exitosamente": "Tu cotización ha sido generada exitosamente",
    "Cotización Confirmada": "Cotización Confirmada",
    "Resumen de tu cotización de cursos marítimos": "Resumen de tu cotización de cursos marítimos",
    "Costo Total": "Costo Total",
    "Nuevos: ${{newCoursesTotal}}": "Nuevos: ${{newCoursesTotal}}",
    "Renovaciones: ${{renewalCoursesTotal}}": "Renovaciones: ${{renewalCoursesTotal}}",
    "Cursos Nuevos:": "Cursos Nuevos:",
    "Renovaciones:": "Renovaciones:",
    "Código: {{abbr}}": "Código: {{abbr}}",
    "(Renovación)": "(Renovación)",
    "Datos del estudiante:": "Datos del estudiante:",
    "Nombre completo:": "Nombre completo:",
    "Documento:": "Documento:",
    "Email:": "Email:",
    "Gobierno/Institución:": "Gobierno/Institución:",
    "Nueva Cotización": "Nueva Cotización",
    "Descargar PDF": "Descargar PDF",
    "Verificar": "Verificar",
    "Ingresa el Código": "Ingresa el Código",
    "Código incorrecto. Intenta de nuevo": "Código incorrecto. Intenta de nuevo",
    "¡Verificación exitosa!": "¡Verificación exitosa!",
    "Por favor, revisa tu correo electrónico para ver la cotización completa." : "Please check your email to see the full quote.",
    "Solicitud de Licencia": "License Application",
    "Completa el formulario para recibir información personalizada": "Complete the form to receive personalized information",
    "Información sobre las licencias": "License Information ",
    "En poco tiempo estaremos contactándole.": "We will be in touch with you shortly.",
    "¡Gracias por su interés!": "Thank you for your interest!",
    "Haga clic para subir": "Click for Upload",
    "o arrastre aquí": "or drag here",
    "Enviar": "Submit",
    "Escribe aquí tu consulta sobre las licencias que necesitas...": "Write your query here about the licenses you need...",
    "No eres tú, somos nosotros": "It's not you, it's us",
    "Volver a la página de inicio": "Go to home page",
    "Estoy de acuerdo que estos cursos son 100% presenciales": "I agree that these courses are 100% in-person",

    // Navbar
    "Home": "Home",

    // Home page (English keys used by new home.tsx)
    "Select the service you need and we'll guide you through the process.": "Select the service you need and we'll guide you through the process.",
    "Request a quote for maritime courses": "Request a quote for maritime courses",
    "Maritime license documentation and renewal": "Maritime license documentation and renewal",
    "Medical fitness certificate for seafarers": "Medical fitness certificate for seafarers",
    "Certificate of Competency – Liberian Registry": "Certificate of Competency – Liberian Registry",
    "Instructor Evaluation": "Instructor Evaluation",
    "Evaluation form for maritime instructors": "Evaluation form for maritime instructors",
    "Panama Maritime Training Solutions": "Panama Maritime Training Solutions",

    // CourseQuote — inline validation messages
    "Please select a government/institution": "Please select a government/institution",
    "Please select your nationality": "Please select your nationality",
    "Please select at least one course": "Please select at least one course",
    "Please verify you are not a robot": "Please verify you are not a robot",
    "You must accept the terms and conditions": "You must accept the terms and conditions",
    "Failed to load courses.": "Failed to load courses.",
    "Select your nationality first to see available courses": "Select your nationality first to see available courses",
    "Select a government/institution to see available courses": "Select a government/institution to see available courses",

    // CourseQuote — terms checkbox
    "Verification": "Verification",
    "I accept the": "I accept the",
    "terms and conditions": "terms and conditions",
    "and the": "and the",
    "privacy policy": "privacy policy",

    // CourseQuote — keys used in the new form (English keys → English values for English mode)
    "Course Quote": "Course Quote",
    "Fill out the form to generate your quote": "Fill out the form to generate your quote",
    "Personal Information": "Personal Information",
    "Name": "Name",
    "Your name": "Your name",
    "Last Name": "Last Name",
    "Your last name": "Your last name",
    "ID or Passport": "ID or Passport",
    "Document number": "Document number",
    "Nationality": "Nationality",
    "Select your nationality": "Select your nationality",
    "Email": "Email",
    "Phone": "Phone",
    "Government/Institution": "Government/Institution",
    "Select the government/institution": "Select the government/institution",
    "New Maritime Courses": "New Maritime Courses",
    "(Search by name or abbreviation)": "(Search by name or abbreviation)",
    "(Search by name, abbreviation or IMO)": "(Search by name, abbreviation or IMO)",
    "Search by name, abbreviation or IMO...": "Search by name, abbreviation or IMO...",
    "Course Renewal": "Course Renewal",
    "(Only courses that allow renewal)": "(Only courses that allow renewal)",
    "I agree that these courses are 100% in-person": "I agree that these courses are 100% in-person",
    "Generating quote...": "Generating quote...",
    "Generate Quote": "Generate Quote",
    "Quote Generated!": "Quote Generated!",
    "Your quote has been generated successfully": "Your quote has been generated successfully",
    "New Courses": "New Courses",
    "Renewals": "Renewals",
    "Student Details": "Student Details",
    "Full name": "Full name",
    "Document": "Document",
    "Government": "Government",
    "New Quote": "New Quote",
    "License Procedure": "License Procedure",
    "Physical Examination": "Physical Examination",
    "Help Us Help You": "Help Us Help You",
    "What information do you need?": "What information do you need?",
  }
};

export default es;